### ISSUE TITLE
Auto create of ViewModel don’t put the Bindingcontext in code behind

### ISSUE THREAD

**Issue by mfranc28** [mfractor/mfractor-feedback#130] opened 2019-07-31 06:35 UTC
When using the auto creation of VieweModel the relative Bindingcontext in XAML code behind wasn’t create.

**Comment by matthewrdev** [comment] 2019-08-01 00:24
Thanks for logging this issue Michelangelo.

Funnily enough @lachlanwgordon has filed a very similar issue at the exact same time. I'm going to close this as a duplicate of #129.

**Closed** 2019-08-01 00:25 UTC

**Comment by lachlanwgordon** [comment] 2019-08-01 00:27
wow, only one minute between the two.
