### ISSUE TITLE
Replace duplicate namespace references does nothing

### ISSUE THREAD

**Issue by lachlanwgordon** [mfractor/mfractor-feedback#211] opened 2020-05-16 23:43 UTC
There are two situations where this refactoring appears and it doesn't work for either. Not sure if the one refactoring should be able to handle both situations or if it should be split.

# 1. Duplicate namespace paths with the same xmlns.
I have the same xmlns in my page twice. This will result in a compile error in XAMLC enabled or a parsing error at runtime.

![Screen Shot 2020-05-17 at 9 35 14 am](https://user-images.githubusercontent.com/29908924/82132312-c3877a80-9821-11ea-9971-a7c08c87084a.png)

MFractor suggests "Replace duplicate namespace reference with converters" which doesn't quite make sense, it should probably just say "Remove duplicate name space",  but the wording sounds like it will fix the problem and remove the reference. Clicking it does nothing.

 #2 Duplicate namespace paths with the different xmlns.
I have my converters name space declared twice with namespace paths(`converters` and `test`), both are used in my xaml. This is valid xaml and will run but it's a waste of code and could be confusing so it should be fixed.

![Screen Shot 2020-05-17 at 9 39 13 am](https://user-images.githubusercontent.com/29908924/82132382-8b346c00-9822-11ea-8a0a-ff22297d6703.png)

MFractor suggests "Replace duplicate namespace references with test"/"Replace duplicate namespace references with converters", depending on which one you right click on. This should remove the xmlns declaration of the unneeded one and fix up any references through the page to the old name space. Clicking it does nothing.

**Comment by matthewrdev** [comment] 2020-05-18 05:39
@lachlanwgordon This was caused by an object equality comparison (rathrr than a value equality comparison) and has been fixed. This will be in the next release, v4.1.3

**Closed by matthewrdev** 2020-05-18 05:39 UTC
Labels: Bug, High Impact, Regression
