### ISSUE TITLE
A Warning When Binding Path Doesn't Exist in ViewModel But Source Is Specified

### ISSUE THREAD

**Issue by Omarkth** [mfractor/mfractor-feedback#174] opened 2019-12-13 14:22 UTC
As you can see from the screenshot below, MFractor gives me a warning that the binding path does not exist in the view model that is specified by the "x:DateType" property, even though my binding has a specific Source.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/822615/70806582-55e3a800-1dc4-11ea-9775-bd34d0e0bab5.png">

##Installation Information

```
--Platform Information--
Operating System: Mac
OS: Unix
OS Service Pack: 
OS Version: Unix 19.2.0.0
--MFractor Information--
Product Name: MFractor
Product Version: 3.9.3
Product Variant: Visual Studio Mac
Product Variant Version: 8.3.11.1
Product SKU: MFRACTOR-VS-MAC
Commit SHA: 8c50ab82483f36fc9fe8f61be2193401e9b4d396
Revision: 3980
Branch: master
Date: 11/12/2019 12:57:24 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by matthewrdev** [comment] 2019-12-13 19:28
@Omarkth Thanks for reporting this issue.

MFractor has not been upgraded to support `RelativeSource`, which is the cause of this issue

**Comment by Omarkth** [comment] 2019-12-13 19:53
That's right, I checked it with an {x:Reference } Source and the warning vanished 👍🏻

**Comment by matthewrdev** [comment] 2020-03-19 11:22
@Omarkth Is this still and issue? If not, I'll close this issue.

**Closed** 2020-05-13 05:15 UTC
Labels: Bug, High Impact
