### ISSUE TITLE
Buggy inserting namespaces via x:Static in XAML

### ISSUE THREAD

**Issue by mrxten** [mfractor/mfractor-feedback#100] opened 2019-02-19 14:46 UTC
Shown in video, please check
[Screen Recording 2019-02-19 at 17.42.29.mov.zip](https://github.com/mfractor/mfractor-feedback/files/2880459/Screen.Recording.2019-02-19.at.17.42.29.mov.zip)

**Comment by matthewrdev** [comment] 2019-02-21 03:05
Hi @mrxten, thanks for reporting this issue.

I'll investigate the cause of the buggy x:Static completions and get back to you.

**Comment by matthewrdev** [comment] 2019-08-01 01:14
@mrxten Visual Studio Mac now has proper support for expression completions with the introduction of the new editor in v8.2. I'm going to close this issue as we are now deprecating our support for the old editor.

**Closed by matthewrdev** 2019-08-01 01:14 UTC
