### ISSUE TITLE
Get binding IntelliSense using x:DataType provided at the root level

### ISSUE THREAD

**Issue by pranshu-aggarwal** [mfractor/mfractor-feedback#201] opened 2020-05-13 05:12 UTC
With the current implementation, we can see binding IntelliSense if x:DataType is set to the current element. But if it is set to root level then binding IntelliSense won't work.

I have created a simple demo to show the issue. In the demo, we have ListTemplate.xaml file. There are two labels on it. First is Name label and the second is Age label. If you see binding IntelliSense worked with Age label because x:DataType is set for itself but it won't work for Name label it should take x:DataType from its parent.
[MfractorDataTypeIssue.zip](https://github.com/mfractor/mfractor-feedback/files/4619959/MfractorDataTypeIssue.zip)

**Comment by matthewrdev** [comment] 2020-05-13 21:45
@pranshu-aggarwal I've located the cause of this issue, it was caused by a typo in the binding context resolution engine:

![image](https://user-images.githubusercontent.com/3260473/81869156-e3673600-95b6-11ea-8f9d-fbf4c3006209.png)

This is fixed and will be in the next release (4.1.1).

**Comment by matthewrdev** [comment] 2020-05-13 21:48
![image](https://user-images.githubusercontent.com/3260473/81869358-435ddc80-95b7-11ea-9f37-db1f04d93b0e.png)

**Comment by pranshu-aggarwal** [comment] 2020-05-14 03:48
Thanks @matthewrdev , I hope this is also working with Name label

**Closed** 2020-05-15 21:05 UTC
