### ISSUE TITLE
Delete Image won't work on last version of MFractor and VS.Mac

### ISSUE THREAD

**Issue by mfranc28** [mfractor/mfractor-feedback#253] opened 2020-06-11 10:17 UTC
##Installation Information

```
--Platform Information--
Operating System: Mac
OS: Unix
OS Service Pack: 
OS Version: Unix 19.5.0.0
--MFractor Information--
Product Name: MFractor
Product Version: 4.2.3.0
Product Variant: Visual Studio Mac
Product Variant Version: 8.6.3.30
Product SKU: MFRACTOR-VS-MAC
Commit SHA: a11efff652d10ff57ccdb73a843411478905c012
Revision: 4468
Branch: master
Date: 9/06/2020 1:56:13 AM (UTC)
Agent: Local
Installed extensions:
	'DeepClean (1.2.5)', 'Xamarin.Forms HotReload extension (1.4.0)', 'LiveXAML (1.3.51)', 'Brute Clean (1.1)', 'Straight8's SpecFlow Integration (1.11.3.0)', 'Essential UI Kit for Xamarin.Forms - Syncfusion (3.0.0.0)', 'XAML Styler (2.0.1)', 'MFractor (4.2.3)', 'Code Coverage (2.0-alpha)', 'MSBuild Editor (2.4.0)', 'Mono Soft Debugger Support (8.6.3)', 'Debugger support for MonoDevelop (8.6.3)', 'F# Language Binding (8.6.3)', 'Version Control Support (8.6.3)', 'NUnit support (8.6.3)', 'Xamarin.Forms Previewer (16.6.0.329)', 'Android Designer (16.6.0.329)', 'Project Web References (8.6.3)', 'Android development (8.6)', 'MonoDevelop Text Editor (8.6.3)', 'Azure Support (8.6.3)', 'Container Tools (1.0.20200415.1)', 'Xamarin Hot Reload (1.0.0.3681761)', 'NuGet Package Management (8.6.3)', 'Text Templating (8.6.3)', 'Xamarin Ide Identity (8.6.3)', 'Web Project Support (8.6.3)', 'Azure Functions development (8.6.3)', 'XamlLanguageService (16.6.0.329)', 'Refactoring Support (8.6.3)', 'iOS Designer (16.6.0.329)', 'CSharp Language Binding (8.6.3)', 'Git support (8.6.3)', 'MonoDevelop Assembly Browser (8.6.3)', 'GTK# Visual Designer (8.6.3)', 'NuGet Packaging (8.6.3)', 'ILAsm Language Binding (8.6.3)', 'Web Editors (8.3)', 'Subversion core engine (8.6.3)', 'Test Runner (8.6.3)', 'Visual Designer Support (8.6.3)', 'Xamarin Test Cloud (8.6)', 'Xamarin Test Cloud - NUnit (8.6)', 'Razor Language Services (8.0.20200408.02)', 'Visual Studio for Mac Tools for Unity (2.6.1.0)', 'Makefile generation (8.6.3)', 'GDB Debugger Support (8.6.3)', 'MonoDevelop Hex Editor (8.6.3)', 'Gettext Translations Support (8.6.3)', 'MonoDevelop Source Editor (8.6.3)', 'Mono Soft Debugger Support for ASP.NET (8.6.3)', 'Azure DevOps Authentication Support (8.6.3)', 'JavaScript and TypeScript (8.3)', 'ASP.NET Core Support (8.6.3)', 'Xamarin.Mac development (8.6)', 'VB.NET Language Binding (8.6.3)', 'XML Editor (8.6.3)', '.Net Core Debugger (8.6.3)', 'Xamarin Addins Core (8.6)', 'Subversion support (8.6.3)', 'Deployment Services for Linux (8.6.3)', 'ChangeLog Add-in (8.6.3)', 'Performance Diagnostics of IDE (8.6.3)', 'Unit Testing core support (8.6.3)', 'Android Deploy (16.6.0.329)', 'ConnectedServices (8.6.3)', 'Extension Developer Tools (8.6.3)', '.NET Core Support (8.6.3)', 'Xamarin Terminal (8.6.3)', 'Azure Mobile App Service (8.6)', 'Deployment Services Core (8.6.3)', 'VsCode Debug Protocol support for MonoDevelop (8.6.3)', 'MonoDevelop Text Editor (8.6.3)', 'DocFood (8.6.3)', 'Regex Toolkit (8.6.3)', 'MonoDevelop Mac Platform Support (8.6.3)', 'Forms Project Support (8.6)', 'Xamarin Ide Extensions (8.6.3)', 'Xamarin Ide Extensions for Mac (8.6.3)', 'Mac Development (8.6)', 'Xamarin Designer (16.6.0.329)', 'iOS development (8.6)'
```

The Delete button or right click on image command don't work as expected

**Comment by matthewrdev** [comment] 2020-06-14 23:26
@mfranc28 Thanks for reporting this issue. I've located the cause of the issues (a null access bug) and fixed it.

This will be available in MFractor 4.2.4, to be released in the next 2-3 days.

**Closed by matthewrdev** 2020-06-14 23:26 UTC
Labels: Bug, High Impact, Mobile
