### ISSUE TITLE
Delete Images not Working on Windows

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#228] opened 2020-05-27 00:26 UTC
The Delete Images feature is not working on Windows. When you select a image on the _Image Asset Manager_ tool window and clicks on delete button nothing happens.

**Comment by matthewrdev** [comment] 2020-06-04 02:04
This sounds like a bug in the display code for the dialog (see DeleteImageAssetWorkUnit). Will need to investigate the UI threading for the work unit handler and make sure it is behaving as expected.

**Comment by matthewrdev** [comment] 2020-06-15 19:33
Duplicate of #253. This has been fixed in MFractor 4.2.4.

**Closed by matthewrdev** 2020-06-15 19:33 UTC
Labels: Bug, Regression, Windows
