### ISSUE TITLE
Navigate to Binding stopped working

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#119] opened 2019-06-21 08:39 UTC
Visual Studio 8.1.1 (build 27), MFractor 3.8.9 (Build 3511), somehow Command+D stopped working (old/new editor)

**Comment by matthewrdev** [comment] 2019-06-22 04:57
Thanks for the report @MBrekhof. This is (again) likely caused by the VS Windows migration work. Let me take a look.

**Comment by matthewrdev** [comment] 2019-06-23 11:53
This has been fixed and will be available in MFractor 3.8.10.

**Comment by matthewrdev** [comment] 2019-06-24 07:02
This has been fixed in MFractor 3.8.10, targeting Visual Studio Mac 8.1.1 (Build 27), and is now available.

**Closed by matthewrdev** 2019-06-24 07:02 UTC
