### ISSUE TITLE
Image importer screen not correct

### ISSUE THREAD

**Issue by MBrekhof** [mfractor/mfractor-feedback#121] opened 2019-06-25 06:32 UTC
The screen looks somewhat distorted, see picture
<img width="917" alt="Screenshot 2019-06-25 at 08 31 09" src="https://user-images.githubusercontent.com/13586354/60074673-c4a04c80-9723-11e9-92a3-3fdd37dba7a2.png">

**Comment by matthewrdev** [comment] 2019-06-25 21:57
Thanks for the report @MBrekhof. I've located the cause of this and resolved it.

This will be fixed in the next MFractor release (3.8.11)

**Comment by matthewrdev** [comment] 2019-06-26 05:45
HI @MBrekhof, I'm currently having issues where updates for MFractor aren't showing in the IDE. You can find the fix in this version of MFractor: https://addins.monodevelop.com/Stable/Mac/8.1.1/MFractor.VS.Mac.MFractor-3.8.11.mpack

**Comment by matthewrdev** [comment] 2019-06-30 01:52
Closing this issue as this has been shipped in 3.8.11

**Closed by matthewrdev** 2019-06-30 01:52 UTC
