### ISSUE TITLE
Image asset import issue

### ISSUE THREAD

**Issue by mfranc28** [mfractor/mfractor-feedback#328] opened 2023-04-14 08:42 UTC
When I try to import new image asset no new resource was imported, in both iOS and Android side.

##Installation Information

Mac Osx Ventura 13.3
Visual Studio 2022 17.5.3 (build 15)
--Platform Information--
Operating System: Mac
OS: Unix
OS Service Pack: 
OS Version: Unix 13.3.0
--MFractor Information--
Product Name: MFractor
Product Version: 5.0.0.0
Product Variant: Visual Studio Mac
Product Variant Version: 17.5.3.15
Product SKU: MFRACTOR-VS-MAC
Installed extensions:	'MFractor (5.0.0)', 'Mono Soft Debugger Support for ASP.NET (17.5.3)', 'Gettext Translations Support (17.5.3)', 'VsCode Debug Protocol support for MonoDevelop (17.5.3)', 'JavaScript and TypeScript (17.3)', '.Net Core Debugger (17.5.3)', 'Mono Soft Debugger Support (17.5.3)', 'NUnit support (17.5.3)', 'Android Deploy (17.5.3.47)', 'Deployment Services Core (17.5.3)', 'Makefile generation (17.5.3)', 'Xamarin Addins Core (17.5)', 'Web Editors (17.4)', 'NuGet Package Management (17.5.3)', 'Android Designer (17.5.3.47)', 'VB.NET Language Binding (17.5.3)', 'Performance Diagnostics of IDE (17.5.3)', 'Xamarin.Forms Editor Extensions (17.5.3.47)', 'Razor Language Services (17.5)', '.NET Core Support (17.5.3)', 'Forms Project Support (17.5)', 'Xamarin Terminal (17.5.3)', 'Web Project Support (17.5.3)', 'JavaScript Debugger (17.5.3)', 'Xamarin Hot Reload (17.5.3.7271633)', 'Text Templating (17.5.3)', 'MonoDevelop Hex Editor (17.5.3)', 'Xamarin Ide Extensions (17.5.3)', 'VisualFSharp (17.5.3)', 'Regex Toolkit (17.5.3)', 'Android development (17.5)', 'ASP.NET Core Support (17.5.3)', 'Debugger support for MonoDevelop (17.5.3)', 'CSharp Language Binding (17.5.3)', 'Xamarin Ide Extensions for Mac (17.5.3)', 'Azure Support (17.5.3)', 'Git support (17.5.3)', 'Unit Testing core support (17.5.3)', 'MonoDevelop Assembly Browser (17.5.3)', 'Refactoring Support (17.5.3)', 'Xamarin Ide Identity (17.5.3)', 'MonoDevelop Mac Platform Support (17.5.3)', 'XML Editor (17.5.3)', 'Xamarin Designer (17.5.3.47)', 'Azure DevOps Authentication Support (17.5.3)', 'iOS development (17.5)', 'Container Tools (1.0.20221213.1)', 'Mac Development (17.5)', 'Azure Mobile App Service (17.5)', 'ConnectedServices (17.5.3)', 'Azure Functions development (17.5.3)', 'Version Control Support (17.5.3)', 'Visual Studio for Mac Tools for Unity (17.5.1.0)', 'Xamarin.Mac development (17.5)', 'Authorization (17.5.3)', 'AddinMaker (17.5.3)', 'XamlLanguageService (17.5.3.47)', 'MonoDevelop Text Editor (17.5.3)', 'Visual Designer Support (17.5.3)'
```

**Comment by matthewrdev** [comment] 2023-04-16 06:37
@mfranc28 I can reproduce this locally (looks like a .NET 7 upgrade behaviour change).

Will work on getting a fix out this week.

**Comment by matthewrdev** [comment] 2023-04-19 03:21
@mfranc28 This is fixed in MFractor 5.1

**Closed by matthewrdev** 2023-04-19 03:21 UTC
