### ISSUE TITLE
Difference between real imported image and imagemshow in Mobile Image Assed Pads

### ISSUE THREAD

**Issue by mfranc28** [mfractor/mfractor-feedback#148] opened 2019-11-20 10:56 UTC
I import, with and without using of Import Asset Wizard some image.
The strange thing is that when I look into Resource Folder I see the correct image, but when I see it with Mobile Asset Image the image look different in rotation, it's 90 degree rotated.

The original image was exactly as see on Mobile Image Asset, but before import it on solution I made a 90 degree rotation via MacOS Preview App, and in fact the file is correctly rotated.

Probably you read some spec parameter on file?
<img width="358" alt="Schermata 2019-11-20 alle 11 52 18" src="https://user-images.githubusercontent.com/6470375/69233201-c9f7ab00-0b8c-11ea-8fcc-15aabf1afddc.png">
<img width="642" alt="Schermata 2019-11-20 alle 11 54 45" src="https://user-images.githubusercontent.com/6470375/69233203-cb28d800-0b8c-11ea-8b33-24e3f91d80bb.png">

**Comment by matthewrdev** [comment] 2019-11-20 11:44
Thanks for reporting this @mfranc28.

Does the image display correctly in your app?

**Comment by matthewrdev** [comment] 2019-11-20 11:45
This could be a display issue in the image manager, for example, it’s not honouring a rotation tag etc when it’s rendering the preview.

**Comment by mfranc28** [comment] 2019-11-20 12:09
Yes

Michelangelo Franco
Il 20 nov 2019, 12:45 +0100, Matthew Robbins <notifications@github.com>, ha scritto:

This could be a display issue in the image manager, for example, it’s not honouring a rotation tag etc when it’s rendering the preview.

**Comment by matthewrdev** [comment] 2019-11-20 20:16
@mfranc28 Can you please attach the original image file to this issue?

**Comment by matthewrdev** [comment] 2019-12-04 04:41
@mfranc28 Following up on this, can you please attach or email the original image asset that is causing this issue?

**Comment by mfranc28** [comment] 2019-12-04 09:30
[cid:507EA231-B7D0-403A-A82C-DC7F6563AD0E]

Il giorno 20 nov 2019, alle ore 21:16, Matthew Robbins <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@mfranc28<https://github.com/mfranc28> Can you please attach the original image file to this issue?

**Comment by matthewrdev** [comment] 2019-12-05 00:23
@mfranc28 Unfortunately the image didn't attach via email. Could you please attach directly using on the GitHub issues page.

**Comment by matthewrdev** [comment] 2019-12-13 03:24
@mfranc28 Following up on this, can you please attach the image in question directly to this ticket (not via GitHubs reply-to-email feature) *or* please email it to me? 

matthew@mfractor.com

**Comment by matthewrdev** [comment] 2019-12-23 23:46
Closing this ticket as I do not have an image sample to reproduce this and I cannot reproduce this based on the steps described.

**Closed by matthewrdev** 2019-12-23 23:46 UTC
Labels: Bug
