### ISSUE TITLE
Inconsistent info from Mfractor 

### ISSUE THREAD

**Issue by kmvickers** [mfractor/mfractor-feedback#200] opened 2020-05-12 10:03 UTC
for the same line of xaml Mfractor is showing me the color of a staticresource and also informing me the static resource doesn't exist

Kevin  
##Installation Information

```
--Platform Information--
Operating System: Windows
OS: Win32NT
OS Service Pack: 
OS Version: Microsoft Windows NT 10.0.18363.0
--MFractor Information--
Product Name: MFractor
Product Version: 4.1.0.0
Product Variant: Visual Studio For Windows
Product Variant Version: 16.0.0.0
Product SKU: MFRACTOR-VS-WINDOWS
Commit SHA: 456a155ffb822243ae788e1ff912fa28be4af2e3
Revision: 4363
Branch: master
Date: 12/05/2020 2:26:45 AM (UTC)
Agent: Local
Installed extensions:
	
```

**Comment by matthewrdev** [comment] 2020-05-13 09:33
Thanks for reporting this issue @kmvickers.

I've done some preliminary investigation work and it looks like this stems from a timing issue between our resource sync engine and our analysis engine. The color adornments live outside these two engines and is displaying the correct behavour.

Continuing to look into this.

**Comment by matthewrdev** [comment] 2020-06-28 02:56
@kmvickers There has been several improvements on the static resource engine since this ticket was filed. Can I confirm that this issue is still present in MFractor v4.2.6?

**Comment by matthewrdev** [comment] 2020-07-08 03:01
@kmvickers I'm unable to reproduce this locally in the current release(s), as such, I'm closing this issue.

If it re-appears, please reopen this ticket and I will investigate.

**Closed by matthewrdev** 2020-07-08 03:01 UTC
Labels: Bug, High Impact
