### ISSUE TITLE
Color Tooltips are too large on Windows

### ISSUE THREAD

**Issue by ravero** [mfractor/mfractor-feedback#231] opened 2020-05-27 01:00 UTC
The color tooltip is appearing to large in Windows:

![Screen Shot 2020-05-26 at 21 58 27](https://user-images.githubusercontent.com/1834963/82964539-1a1c5380-9f9c-11ea-9dc4-e49617a3b773.png)

It looks like the tooltip view is taking all the width available on the screen to render itself. I'm not sure if you're using shared logic or if this tooltip is implemented in WPF. It's probably a matter of constraining the width of this preview.

**Comment by matthewrdev** [comment] 2020-06-01 01:16
These color tooltips use Xwt to generate the UIs; this is likely the cause of this strange rendering behaviour.

To resolve, the color tooltip view should be ported from XWT to WPF.

**Comment by ravero** [comment] 2020-06-01 01:57
I'm reopening this Issue and assigning it to me as a task of porting this feature to WPF in Windows.

**Comment by matthewrdev** [comment] 2020-06-01 02:50
Oops! I didn't mean to close this. 🤦‍♂️

**Comment by matthewrdev** [comment] 2020-06-28 02:15
This has been fixed and will be available in MFractor v4.2.7.

**Closed by matthewrdev** 2020-06-28 02:15 UTC
Labels: Bug, High Impact, Windows
