### ISSUE TITLE
'Go To Implementation' is not working and is missing from context menu

### ISSUE THREAD

**Issue by akamud** [mfractor/mfractor-feedback#125] opened 2019-07-16 14:26 UTC
Since the last version of MFractor I'm missing the "Go To Implementation" option from the context menu:

![image](https://user-images.githubusercontent.com/954102/61301155-ba6ced80-a7b9-11e9-9f61-919ca7b81683.png)

Also, using the Option + D shortcut doesn't navigate anymore, even though I double-checked my keybindings are correct:

![image](https://user-images.githubusercontent.com/954102/61301208-d40e3500-a7b9-11e9-96b4-e379bddc4b87.png)

This was a very useful feature for code that relies heavily on Interfaces and Abstract classes.
Am I missing something? Was it removed for some reason?

**Comment by matthewrdev** [comment] 2019-07-30 22:42
Hi @akamud, can you please try the steps outlined here and then report back: https://www.mfractor.com/blogs/news/mfractor-auto-updates-known-issue

**Comment by akamud** [comment] 2019-07-31 13:54
Hi @matthewrdev, I tried that and I can see that many MFractor commands are available, it is just a problem with that specific command.

![image](https://user-images.githubusercontent.com/954102/62217652-62b9af00-b381-11e9-85af-06f537e5d4d7.png)

In fact, investigating a bit more, I noticed that it does show up when I'm using the new C# editor. I don't use the new editor because it lacks Vim support, so I'm on the old editor at the moment. it looks like something is preventing that action from being recognized on the old editor.

**Comment by matthewrdev** [comment] 2019-08-01 00:54
I'll take a look and see what's happening. Technically we deprecated support for "Go To Implementation" once the native implementation came out so this could be the cause. It *should* still be online under the hood but this indicates it is not.

**Comment by matthewrdev** [comment] 2019-12-04 23:10
@akamud Following up on this to confirm that this is still an issue?

As the old editor is deprecated in Visual Studio Mac, it's unlikely that we will support this in future. We have open sourced the ["Go To Implementation"](https://github.com/matthewrdev/vs-mac-extension-samples/tree/master/GoToImplementation/GoToImplementation) feature which could be ported into a stand alone extension.

Another option is that I can provide some assistance upgrading the VIM editor extension.

**Comment by matthewrdev** [comment] 2019-12-06 22:12
@akamud Unfortunately a lot of the extensibility points to reactivate this feature no longer exist or are unstable in the new versions of Visual Studio Mac. It's unlikely we could re-enable this now even if we wanted to.

I'm closing this issue.

**Closed by matthewrdev** 2019-12-06 22:12 UTC
Labels: Mac, Regression, bug
